[features]
seeds = false
skip-lint = false

[programs.localnet]
auction = "5qCJsXGjyDwk9zn4TnarTbq6A3TBvDbzbEf4drQkY87E"

# [programs.devnet]
# auction = "7QWxoHUMnEJAWr2LxpBzSKSgD9us2thCMeMZuiPRA9Ns"

[registry]
url = "http://127.0.0.1:8899"

# [registry]
# url = "https://api.devnet.solana.com"

[provider]
cluster = "Localnet"
wallet = "/home/tung/Downloads/wallet-keypair.json"

# [provider]
# cluster = "Devnet"
# wallet = "/path/to/wallet-keypair.json"

[scripts]
# anchor test
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
# anchor run test
client = "yarn run ts-node client/*.ts"
